buildscript {
    repositories {
        maven { url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.neoforged.gradle', name: 'userdev', version: '7.0.119'
    }
}

apply plugin: 'java'
apply plugin: 'net.neoforged.gradle.userdev'

group = 'com.example'
version = '1.0'
base { archivesName = 'enchantment_upper' }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.neoforged:neoforge:21.0.163'
}

minecraft {
    mappings channel: 'official', version: '1.21'
}
